#
# Local setup
#

version: '3'
services:
  nginx:
    container_name: sneaker_test_nginx
    image: nginx:latest
    ports:
      - "8090:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    networks:
      the_net:
        aliases:
          - 'sneaker-test'
  app:
    container_name: app
    build:
      context: ./
      dockerfile: docker/app.docker
    environment:
      VIRTUAL_HOST: obotService
      DB_HOST: database
      DB_PORT: 5432
      PHP_IDE_CONFIG: serverName=sneakerTest
    volumes:
      - ./:/var/www
    networks:
      - the_net
    links:
      - database
      - test_database
      - selenium

  database:
    container_name: sneaker_test_db
    image: postgres:10
    environment:
      POSTGRES_DB: sneaker_test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - sneaker_test_db_data:/var/lib/postgresql/data
    networks:
      - the_net

  test_database:
    container_name: test_sneaker_test_db
    image: postgres:10
    environment:
      POSTGRES_DB: test_sneaker_test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - test_sneaker_test_db_data:/var/lib/postgresql/data
    networks:
      - the_net



  selenium:
    container_name: selenium
    build:
      context: ./
      dockerfile: docker/selenium-vnc.docker
    environment:
      SCREEN_WIDTH: 1500
      SCREEN_HEIGHT: 1200
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - the_net


volumes:
  sneaker_test_db_data:
  test_sneaker_test_db_data:
  selenium_downloads:

networks:
  the_net:
    driver: "bridge"
